### ISSUE TITLE
Scroll-Funktion für die Meldungserfassung (Student und Admin)

### ISSUE THREAD

**Issue by tatjanagraf** [FacMan-SW-Project-2016/supertrooper#42]
Scrollfunktion funktioniert nirgends, bei Meldungen von Admin zumindest auch nicht

**Comment by tatjanagraf** [comment]
Das ist echt behindert, geht in der mobilen ansicht auch nur hin und wieder mal, aber meistens nicht

**Comment by nico-kn** [comment]
Bekannt, ist aber hart zu fixen.
