### ISSUE TITLE
Admin-Funktion - DELETE funktioniert bei mir nicht

### ISSUE THREAD

**Issue by lrvllmr** [FacMan-SW-Project-2016/supertrooper#46]
Ich kann als Admin aus irgendeinem Grund nicht Meldungen löschen...
Wollen wir das "Delete" übersetzen der Einheitlichkeit halber?

**Comment by Th0masHammer** [comment]
kein plan, bei mir gehts
müsste man aber auch refresh und co übersetzen. is für mich jetzt ned so wichtig
