### ISSUE TITLE
TRansatlantikinsitut hat keine Räume, daher kann man keine Meldugen anlegen

### ISSUE THREAD

**Issue by lrvllmr** [FacMan-SW-Project-2016/supertrooper#47]
Ist vielleicht jetzt nur was wegen Vollständigkeit und so, und vielleicht ist das gar nicht notwendig. wir sollten nur daran denken, dass wir während der Präsi dann keine Meldung dafür anlegen...

**Comment by lrvllmr** [comment]
gilt auch für Maxstrasse und Hauptgebäude B

**Comment by lrvllmr** [comment]
Könnten vielleicht Sonstige so bei allen hinzufügen für Toiletten und Flure... Kann man ja dann in der Beschreibung genauer beschreiben

**Comment by nico-kn** [comment]
Darfst du gerne tun und dementsprechend das facilitymgmt.sql file updaten :)
