### ISSUE TITLE
Nutzer FAcility Management? 

### ISSUE THREAD

**Issue by lrvllmr** [FacMan-SW-Project-2016/supertrooper#49]
Laut unserer USE CASES haben wir drei Nutzer: Student, FacMan und Admin... FacMan gibt es noch nicht im Anmeldungsbereich? Sollen wir unseren USE CASE ändern oder habt ihr noch nen Nutzer?

**Comment by nico-kn** [comment]
Auch hier: leg dir gerne nen Nutzer an und exportiere das db file und update dementsprechend das facilitymgmt.sql file :)
